manifest:
  remotes:
    - name: sadekbaroudi
      url-base: https://github.com/sadekbaroudi
  projects:
    - name: zmk-fingerpunch-vik
      remote: sadekbaroudi
      revision: feature/zmk-v0.4-migration
      import: config/deps.yml
    - name: zmk-fingerpunch-controllers
      remote: sadekbaroudi
      revision: feature/zmk-v0.4-migration
      import: config/deps.yml
